pipeline {
    agent any
    
    environment {
     
     scannerHome = tool 'sonar-scanner'
     DOCKER_IMAGE = "533267075370.dkr.ecr.ap-south-1.amazonaws.com/development/api-dev:${BUILD_NUMBER}"
            
    }

    stages {

        stage('Cleaning Workspace') {
            steps {
                
                cleanWs()
            }
        }


        stage('Clone Repository') {
            steps {
                checkout scm
            }
        }
        
        
        stage('Static Code Analysis') {
            parallel {
                stage('SonarQube Analysis') {
                    steps {
                        withSonarQubeEnv('sonar-server') {
                              sh '''
                              
                                     ${scannerHome}/bin/sonar-scanner \
                                     -Dsonar.projectName=pythonapp \
                                     -Dsonar.sources=api/ \
                                     -Dsonar.projectKey=pythonapp
                                     
                                '''
                            }
                    }
                }

                stage('Owasp Dependency Check') {
                     steps {
                        catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                            timeout(time: 60, unit: 'MINUTES') {
                                dependencyCheck additionalArguments: '--scan ./', odcInstallation: 'dp'
                                dependencyCheckPublisher pattern:'dependency-check-report.xml'
                                
                            }
                        }
                    }
                }         
        
            }
        }

        stage("SonarQube Quality Gate") {
            steps {
                script {
                    timeout(time: 1, unit: 'HOURS') {
                        def qg = waitForQualityGate()
                        if (qg.status != 'OK') {
                            error "Pipeline aborted due to quality gate failure: ${qg.status}"
                        }
                    }
                }
            }
        }


        stage('docker') {
            steps {
                
               dir('api') {
                   
                    sh 'sudo docker build  -t $DOCKER_IMAGE .' 
                }
                
            }
        }

        stage('Anchore Image Scan') {
            steps {
                script {
                   
                    sh """
                    
                       sudo grype $DOCKER_IMAGE -o json > anchore-scan.json
                       
                    """
                    archiveArtifacts artifacts: 'anchore-scan.json', allowEmptyArchive: true
                }
            }
        }
        
        stage('Push Docker Image to ECR') {
            steps {
                script {
                    
                    withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'aws-cred', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                        
                            sh '''
                                aws ecr get-login-password --region ap-south-1 | sudo docker login --username AWS --password-stdin 533267075370.dkr.ecr.ap-south-1.amazonaws.com
                                sudo docker push $DOCKER_IMAGE 
                            '''
                    } 
                }
            }
        }
        
    }
}
